# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calynew <- function(ynew, vl) {
    .Call(`_HiRRM_calynew`, ynew, vl)
}

fast_mvlmmthreads <- function(thread, Y, gnew, vl, sth) {
    .Call(`_HiRRM_fast_mvlmmthreads`, thread, Y, gnew, vl, sth)
}

MatMult <- function(A, B) {
    .Call(`_HiRRM_MatMult`, A, B)
}

eigenMatMult <- function(A, B) {
    .Call(`_HiRRM_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_HiRRM_eigenMapMatMult`, A, B)
}

CLegendre <- function(x, s) {
    .Call(`_HiRRM_CLegendre`, x, s)
}

